server {
    listen 8090;
    server_name _;

    location / {
        root /opt/MealPlannerFrontend/;
        index index.html;
        try_files $uri $uri/ @backend;
    }

    location @backend {
        proxy_pass http://localhost:8080;
    }
}